### ISSUE TITLE
Attributes Syntax Highlighting with Strings

### ISSUE THREAD

**Issue by opensourcecheemsburgers** [poliorcetics/tree-sitter-just#1]
Attribute syntax highlight does not seem to work when including strings. 

I could be doing something wrong though.

Note: Everything looks fine in VSCodium and also `just --unstable --fmt --check` exits without an error.

![2024-12-21-231415_hyprshot](https://github.com/user-attachments/assets/17cd7644-a6c9-424a-b6a7-3fe4d9f63286)

**Comment by poliorcetics** [comment]
Thanks for the report!

Could you send me an example file (minimized would be awesome, but don't worry too much about it) ?

I'm not immediately seeing the diff from the screenshot so I can't diagnose what is happening here

**Comment by poliorcetics** [comment]
Additionally, can you tell me what version of helix (`hx --version`) you're using ? The cause may be an outdated grammar

**Comment by opensourcecheemsburgers** [comment]
`hx --version` returns `helix 24.7`.

Here's a minimal repro:
```
[linux]
build:
    RUSTFLAGS="-C panic=abort" \
    cargo tauri build \
    --debug 
    --target x86_64-unknown-linux-gnu \
    -- \
    -Z build-std=std,panic_abort \
    -Z build-std-features=panic_immediate_abort

[windows]
build:
    RUSTFLAGS="-C panic=abort" \
        cargo tauri build \
        --debug \
        --target x86_64-pc-windows-msvc \
        -- \
        -Z build-std=std,panic_abort \
        -Z build-std-features=panic_immediate_abort

[linux]
build-release:
    RUSTFLAGS="-C panic=abort" \
    cargo tauri build \
    --target x86_64-unknown-linux-gnu \
    -- \
    -Z build-std=std,panic_abort \
    -Z build-std-features=panic_immediate_abort \
    -Z build-std-features="optimize_for_size"

[windows]
build-release:
    RUSTFLAGS="-C panic=abort" \
        cargo tauri build \
        --target x86_64-pc-windows-msvc \
        -- \
        -Z build-std=std,panic_abort \
        -Z build-std-features=panic_immediate_abort \
        -Z build-std-features="optimize_for_size"
```

**Comment by opensourcecheemsburgers** [comment]
Also, mb, there is no diff in the file. I just separated it into two windows so that the text would be easier to view on the screenshot.

**Comment by poliorcetics** [comment]
<img width="636" alt="Screenshot 2024-12-26 at 21 56 05" src="https://github.com/user-attachments/assets/36bd0cba-ae38-435c-ae9b-e0365afd957f" />

Renders nicely on latest master, I'm going to put that down to helix 24.7 not yet using my grammar.

Feel free to reopen if it happens again on latest master :)

**Comment by opensourcecheemsburgers** [comment]
Can confirm, just updated my helix config with the latest commit tag and it works.

```
[[grammar]]
name = "just"
source = { git = "https://github.com/poliorcetics/tree-sitter-just", rev = "180bb15d64c63585c4f65c551350048f21987bcb" }
```
